Update node.yml
the-medium/fabric-softener pull request #9
Opened 2021-11-29 05:44 UTC by mhyangjin

Check if nvm is installed and install curl.

2021-11-29 06:34 UTC, sukill requested changes

2021-11-29 06:34 UTC, sukill commented on roles/install/tasks/node.yml
> +
중복된 코드 제거해주세요~

2021-11-29 06:36 UTC, sukill commented
@mhyangjin 
PR Description이 변경 내용과 관련이 없어 보입니다.
확인 부탁드리겠습니다.

2021-11-29 06:43 UTC, sukill reviewed
curl -O  http://download/url/file || wget http://download/url/file 2>/dev/null

이런 식의 접근도 재미있어 보입니다

2021-11-29 06:44 UTC, mhyangjin commented on roles/install/tasks/node.yml
> +
curl check 로직이 추가되었어야 했는데 nvm이 들어갔네요. 수정했습니다.

2021-11-29 06:53 UTC, mhyangjin commented
흠...  어쨌든 둘다 실행하긴 할테니 뭐든 하나는 성공 하겠네요.

2021-11-29 06:55 UTC, justin-themedium commented
> 

실제 해보시면 알겠지만, 실패한 경우에만 뒤쪽이 실행될겁니다.

2021-11-29 06:59 UTC, sukill commented
@justin-themedium 앞쪽이 성공할 경우 뒤쪽은 실행 안될 수도 있나요?

2021-11-29 07:00 UTC, sukill commented
재미있네요 ㅎㅎ..
![image](https://user-images.githubusercontent.com/10053875/143822325-c7a270fc-4d72-4f7d-87c3-286a41331e86.png)

2021-11-29 07:02 UTC, mhyangjin commented
에러 처리는 어떻게 될까요? ansible에 error message가 넘어갈까요?

2021-11-29 07:16 UTC, sukill commented
@mhyangjin 네네
[링크](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html#return-values) 들어가보시면
ansible shell 모듈의 return 값들을 확인하실 수 있습니다.

2021-11-29 07:17 UTC, mhyangjin commented
아하~ 리턴 타입들이 여기 있군요! 궁금했었음... 땡큐!!

2021-11-29 07:27 UTC, sukill commented
@mhyangjin 넵넵  PR 메시지랑 커밋만 수정 부탁드리겠습니다.
PR 메시지를 보면
"nvm이 설치되어 있는지 확인하고 curl을 설치합니다"라고 되어 있어서요
"nvm을 설치하기 전 curl이 설치되어 있는지 확인하고 설치되어 있다면 curl을 그렇지 않다면 wget을 이용하여 nvm을 설치합니다." 라고 하시면 될 것 같습니다.

그리고 커밋을 한개로 만들어서 올려주시구요 커밋 메시지도 작업하신 내용으로 변경부탁드리겠습니다.

2021-11-29 07:28 UTC, sukill requested changes

2021-11-29 07:28 UTC, sukill commented on roles/install/tasks/node.yml
> +  ignore_errors: true
nvm이 설치되어 있다면 curl 설치 여부를 확인하는 task도 스킵할 수 있을 것 같습니다.

2021-11-29 07:29 UTC, sukill commented on roles/install/tasks/node.yml
> +  ignore_errors: true
아니면 Install nvm block에 포함시켜도 될 것 같구요

2021-11-29 07:43 UTC, mhyangjin commented on roles/install/tasks/node.yml
> +  ignore_errors: true
변경하고 테스트 한번 돌려보고 업데이트하죠.

2021-11-30 09:24 UTC, justin-themedium commented
1. 최신으로 rebase하시고
2. commit 하나로 합쳐서 업데이트해주시고
3. 어느 이슈에 대한 수정인지 commit message에 서술 바랍니다.

commit message는 다음 형식을 가급적 지켜주세요. 제목은 80자 이내를 권장합니다만, 넘어가도 되고, 너무 길지 않게만 해주시면 됩니다.
상세 사항 서술이 필요 없는 경우 제목만 적어주셔도 무방합니다.

```
이슈 번호를 포함한 간략한 제목

해당 commit에 대한 상세 사항
```

2021-12-02 08:21 UTC, closed without merging